name: GitHub Metrics

on:
  schedule:
    - cron: "30 18 * * *"  # Every day at 12:00 AM IST
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: akhilsaysomething
          template: classic
          base: header, activity, community, repositories, metadata

          
