name: Profile Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'  # daily (adjust your CRON)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate stats in README
        uses: ictinus0222/profile-readme-stats@v3
        with:
          token: ${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}
          template: './README.md'
          readme: './README.md'
      - name: Commit and push changes
        run: |
          git config user.name 'Akhil Sharma'
          git config user.email 'sharmakhil1704@gmail.com'
          git add README.md
          git commit -m 'Update profile stats' || echo "No changes"
          git push
